Repository GDG-on-Campus-KHU/SDGP_team3_BE, pull requests merged in 2025-05, with the labels that each got.

#7 Resolved #4, decoration API
  .github/workflows/deploy.yaml
  .gitignore
  app/config.py
  app/controllers/decoration_controller.py
  app/controllers/decoration_user_controller.py
  app/controllers/user_controller.py
  app/core/__init__.py
  app/core/auth.py
  app/core/security.py
  app/dependencies/__init__.py
  app/dependencies/auth.py
  app/main.py
  app/models/challenge_model.py
  app/models/decoration_model.py
  app/models/decoration_user_model.py
  app/models/stamp_model.py
  app/repositories/decoration_repository.py
  app/repositories/decoration_user_repository.py
  app/services/decoration_service.py
  app/services/decoration_user_service.py
  deploy/run_in_production.sh
  deploy/run_in_test.sh
  docker-compose-production.yml
  docker-compose-test.yml
  migrations/migrate.py
  migrations/run_docker_postgres.sh
  migrations/sql/003_create_decorations_table.sql
  migrations/sql/004_create_challenges_table.sql
  migrations/sql/005_create_stamps_table.sql
  migrations/sql/006_create_decoration_user_table.sql
  migrations/sql/007_create_challenge_decoration_table.sql
  migrations/sql/008_create_challenge_stamp_table.sql
  pyproject.toml
Labels: enhancement

#9 Update deploy.yaml
  .github/workflows/deploy.yaml
Labels: bug

#11 challenge and stamp: API 추가
  app/controllers/challenge_controller.py
  app/controllers/stamp_controller.py
  app/database/database.py
  app/main.py
  app/models/challenge_model.py
  app/models/challenge_stamp_model.py
  app/models/stamp_model.py
  app/repositories/challenge_repository.py
  app/repositories/challenge_stamp_repository.py
  app/repositories/stamp_repository.py
  app/services/challenge_service.py
  app/services/stamp_service.py
  migrations/sql/004_create_challenges_table.sql
Labels: enhancement

#10 Vision api for OCR and tumbler detection
  app/controllers/vision_controller.py
  app/services/vision_service.py
Labels: enhancement

#12 gemini api: challengeResponse 관련 fix 및 gemini api 연동
  app/controllers/stamp_controller.py
  app/models/challenge_model.py
  app/services/vision_service.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#13 test oauth: POST /api/users/test로 JWT 위변조 막기
  app/controllers/user_controller.py
Labels: help wanted

#15 gemini modified
  .DS_Store
  app/config.py
  app/controllers/vision_controller.py
  app/main.py
  app/services/gemini_service.py
  app/services/vision_service.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#16 Update README.md - Attached demo video
  README.md
Labels: documentation
